### ISSUE TITLE
[BUG] Crash when adding a mod from steam

### ISSUE THREAD

**Issue by zalexki** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#100] opened 2020-07-11 17:20 UTC
**Describe the bug**
Crash when importing some mods from steam, this one below is an example.

**To Reproduce**
Steps to reproduce the behaviour:
1. Steam mods 
2. Add Steam Mod 
3. enter `https://steamcommunity.com/sharedfiles/filedetails/?id=2158809703`
4. click import

**OS Version (required):**
 - OS: [e.g. Windows 10 1809]

**Comment by Foxlider** [comment] 2020-07-11 17:21
Give me a second to check..

**Comment by Foxlider** [comment] 2020-07-11 17:30
Ok I'm an idiot... 
I had no idea steam IDs were so big. 
So yeah, I'll do a hotfix soon to fix this issue. In the meantime, you'll have to use this mod in local

**Comment by Foxlider** [comment] 2020-07-11 17:54
Aaaad fixed ! 
I'll get you a release ready in a few

**Comment by zalexki** [comment] 2020-07-11 18:03
sweet ! 🚀 🚢  \o/

**Comment by Foxlider** [comment] 2020-07-11 18:03
I'm not closing the issue yet. it will be fixed in the 1.7 release. 
In the meantime, you have your very own release ;)

**Comment by MAJThomasASOT** [comment] 2020-09-05 03:14
Hey there. 
I'm getting the same with our mod when trying to add it.
http://steamcommunity.com/sharedfiles/filedetails/?id=2204146686
The name is shorter than other mods so I'm not sure what's happening.

**Comment by Saborknight** [comment] 2020-09-05 04:30
@MAJThomasASOT the issue isn't the length of the name, but the size of the ID (the series of numbers at the end of your link)
Like Foxlider says above, the issue is fixed properly in the next release of FASTER. In the meantime, you may manually download the mod and load it as a local mod instead.

**Comment by Foxlider** [comment] 2020-10-23 13:40
Fixed in 1.7a

**Closed by Foxlider** 2020-10-23 13:40 UTC
Labels: CRITICAL, bug
